### ISSUE TITLE
Track cass-operator ticket 293 to allow for specifying additional labels on client service

### ISSUE THREAD

**Issue by jeromatron** [k8ssandra/k8ssandra#486] opened 2021-03-03 04:20 UTC
Tracking completing cass-operator [issue 239](https://github.com/datastax/cass-operator/issues/293), which is to allow for specifying additional labels on client service.

**Comment by jdonenine** [comment] 2021-03-03 12:50
This is a duplicate of #478 so I'm going to close this one.

**Closed by jdonenine** 2021-03-03 12:50 UTC
