### ISSUE TITLE
K8SSAND-43 ⁃ Multiple installs per Kubernetes cluster is broken in current integration tests

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra#644] opened 2021-04-08 11:19 UTC
## Bug Report
**Describe the bug**
My integration test failed with the wrong timeout set, so the AfterSuite was not run and the previous namespace was not cleaned up. The next run failed with the following error message:

```
CustomResourceDefinition",
                                        "Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole \"k8ssandra-cass-operator-cr\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key \"meta.helm.sh/release-namespace\" must equal \"k8ssandra2021040814132607\": current value is \"k8ssandra2021040814102907\"",
```

Indicating we're deploying a Clusterscoped installation with the default installation.

**To Reproduce**
For example, run the Medusa test with not enough time for it actually succeed and go will kill it.

``/usr/bin/go test -timeout 30s -run '^TestMedusaDeploymentScenario$' github.com/k8ssandra/k8ssandra/tests/integration``

Run it afterwards with larger timeout. And the failure message appears since we can't install more than one k8ssandra per Kubernetes cluster.

**Expected behavior**
Other namespaces shouldn't block installation.

* Kubernetes version information:
kind 0.10.0 with kube 1.20.2

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-43) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-43
┆priority: Medium

**Comment by jsanda** [comment] 2021-04-08 11:50
Installing multiple releases across different namespaces still works as expected, provided the release names are unique. I tested and verified this. The problem is that the test uses the same release name. See [here](https://github.com/k8ssandra/k8ssandra/blob/main/tests/integration/steps/integration_steps.go#L110).

**Comment by bradfordcp** [comment] 2022-04-12 05:32
It sounds like the fix is just to change release names. Is that acceptable?

**Comment by jsanda** [comment] 2022-04-12 22:11
I'm closing this as won't fix. I'd consider it an enhancement that is no longer needed.

**Closed by jsanda** 2022-04-12 22:11 UTC
Labels: bug, needs-triage, zh:Assess/Investigate
