### ISSUE TITLE
Getting Started installation fails: `helm install k8ssandra-tools …` errors with `failed pre-install: timed out waiting for the condition`

### ISSUE THREAD

**Issue by michaelsembwever** [k8ssandra/k8ssandra#143] opened 2021-01-04 20:36 UTC
## Bug Report

**Describe the bug**

The instructions on https://k8ssandra.io/docs/getting-started/ do not work.

**To Reproduce**

```
❯ kubectl cluster-info
Kubernetes control plane is running at https://kubernetes.docker.internal:6443
KubeDNS is running at https://kubernetes.docker.internal:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

```
❯ helm repo add k8ssandra https://helm.k8ssandra.io/
"k8ssandra" has been added to your repositories
```

```
❯ helm repo add traefik https://helm.traefik.io/traefik
"traefik" has been added to your repositories
```

```
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "datastax" chart repository
...Successfully got an update from the "traefik" chart repository
...Successfully got an update from the "k8ssandra" chart repository
Update Complete. ⎈Happy Helming!⎈
```

```
❯ helm install k8ssandra-tools k8ssandra/k8ssandra
W0104 20:48:02.872044   50075 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0104 20:48:02.892853   50075 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0104 20:48:02.905543   50075 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0104 20:48:03.007285   50075 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0104 20:48:04.606131   50075 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration

Error: failed pre-install: timed out waiting for the condition
```

The previous command with debug outputs:
```
❯ helm install --debug k8ssandra-tools k8ssandra/k8ssandra
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/mick/Library/Caches/helm/repository/k8ssandra-0.17.1.tgz

client.go:122: [debug] creating 1 resource(s)
W0104 21:04:12.959779   51691 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
install.go:141: [debug] CRD cassandrabackups.cassandra.k8ssandra.io is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
W0104 21:04:12.972515   51691 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
install.go:141: [debug] CRD cassandrarestores.cassandra.k8ssandra.io is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
W0104 21:04:12.985723   51691 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
install.go:141: [debug] CRD reapers.reaper.cassandra-reaper.io is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
W0104 21:04:13.076437   51691 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
install.go:141: [debug] CRD cassandradatacenters.cassandra.datastax.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD alertmanagerconfigs.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD probes.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:122: [debug] creating 1 resource(s)
install.go:141: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
W0104 21:04:14.490756   51691 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission" PodSecurityPolicy
client.go:122: [debug] creating 1 resource(s)
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission" ServiceAccount
client.go:122: [debug] creating 1 resource(s)
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission" ClusterRole
client.go:122: [debug] creating 1 resource(s)
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission" ClusterRoleBinding
client.go:122: [debug] creating 1 resource(s)
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission" Role
client.go:122: [debug] creating 1 resource(s)
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission" RoleBinding
client.go:122: [debug] creating 1 resource(s)
client.go:268: [debug] Starting delete for "k8ssandra-tools-kube-prome-admission-create" Job
client.go:122: [debug] creating 1 resource(s)
client.go:477: [debug] Watching for changes to Job k8ssandra-tools-kube-prome-admission-create with timeout of 5m0s
client.go:505: [debug] Add/Modify event for k8ssandra-tools-kube-prome-admission-create: ADDED
client.go:544: [debug] k8ssandra-tools-kube-prome-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:505: [debug] Add/Modify event for k8ssandra-tools-kube-prome-admission-create: MODIFIED
client.go:544: [debug] k8ssandra-tools-kube-prome-admission-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: failed pre-install: timed out waiting for the condition
helm.go:81: [debug] failed pre-install: timed out waiting for the condition
```

**Expected behavior**

`k8ssandra-tools` installs.

**Environment:**

* Helm charts version info
```
❯ helm ls -A
NAME           	NAMESPACE	REVISION	UPDATED                             	STATUS	CHART           	APP VERSION
k8ssandra-tools	default  	1       	2021-01-04 21:31:06.333882 +0100 CET	failed	k8ssandra-0.17.1	3.11.7
```

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 

* Kubernetes version information:
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
 
via docker desktop (2.5.3 (50261))

**Comment by jdonenine** [comment] 2021-01-04 20:46
Just as a point of reference, I wasn't able to reproduce this using kind with the same 1.19.3 version of kubernetes.  I did see it when I tried to deploy to a Docker Desktop cluster though, so it seems to have more to do with Docker Desktop than the k8s version.

**Comment by jdonenine** [comment] 2021-01-05 13:55
I was eventaully able to reproduce this on Docker Desktop, and ultimately I hit a few different issues.

First was a docker networking issue, there was a relatively simple resolution for that where expanding the network space granted to Docker Desktop allowed for the read errors to stop happening.

The step that was timing out was a lookup of a secret.  Switching to a network space that didn't overlap with my local network space did the trick:

![image](https://user-images.githubusercontent.com/7901615/103653850-1c339100-4f33-11eb-9d75-eb503962ae4f.png)

However, once I got past that and things properly installed, things could not fully start up, in the end because of storage class issues:

```
% kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                                            READY   STATUS     RESTARTS   AGE     IP           NODE             NOMINATED NODE   READINESS GATES
default       cass-operator-65956c4f6d-dv496                                  1/1     Running    0          5m9s    10.1.0.6     docker-desktop   <none>           <none>
default       grafana-deployment-749d479c4d-cjldh                             1/1     Running    0          2m52s   10.1.0.15    docker-desktop   <none>           <none>
default       k8ssandra-cluster-dc1-default-sts-0                             0/2     Pending    0          2m51s   <none>       <none>           <none>           <none>
default       k8ssandra-cluster-grafana-operator-k8ssandra-594c4fb4f4-9k9vz   1/1     Running    0          3m14s   10.1.0.9     docker-desktop   <none>           <none>
default       k8ssandra-cluster-k8ssandra-stargate-5575748b6d-7lwfc           0/1     Init:0/1   0          3m14s   10.1.0.10    docker-desktop   <none>           <none>
default       k8ssandra-cluster-reaper-operator-k8ssandra-7f5f96c478-dhcbb    1/1     Running    0          3m14s   10.1.0.11    docker-desktop   <none>           <none>
default       k8ssandra-tools-kube-prome-operator-6d57f758dd-nj7wk            1/1     Running    0          5m9s    10.1.0.7     docker-desktop   <none>           <none>
default       prometheus-k8ssandra-cluster-prometheus-k8ssandra-0             2/2     Running    0          3m4s    10.1.0.13    docker-desktop   <none>           <none>
kube-system   etcd-docker-desktop                                             1/1     Running    0          5m16s   172.16.0.3   docker-desktop   <none>           <none>
kube-system   kube-apiserver-docker-desktop                                   1/1     Running    0          5m30s   172.16.0.3   docker-desktop   <none>           <none>
kube-system   kube-controller-manager-docker-desktop                          1/1     Running    0          5m13s   172.16.0.3   docker-desktop   <none>           <none>
kube-system   kube-scheduler-docker-desktop                                   1/1     Running    0          5m21s   172.16.0.3   docker-desktop   <none>           <none>
```
The cluster-dc pods are failing to start:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  78s (x6 over 5m33s)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
```

The standard filesystem storage class doesn't work with Docker Desktop:

```
% kubectl describe PersistentVolumeClaim server-data-k8ssandra-cluster-dc1-default-sts-0
Name:          server-data-k8ssandra-cluster-dc1-default-sts-0
Namespace:     default
StorageClass:  standard
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/managed-by=cass-operator
               cassandra.datastax.com/cluster=k8ssandra-cluster
               cassandra.datastax.com/datacenter=dc1
               cassandra.datastax.com/rack=default
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    k8ssandra-cluster-dc1-default-sts-0
Events:
  Type     Reason              Age                  From                         Message
  ----     ------              ----                 ----                         -------
  Warning  ProvisioningFailed  38s (x8 over 6m59s)  persistentvolume-controller  storageclass.storage.k8s.io "standard" not found
```

Given that local deployment via Docker Desktop isn't really a primary use case, I'm not sure how much priority we can give to this.  Docker Desktop is really quick to start using, since it's just there, so it would be great if it worked as a way to get people going quickly, but kind is also an easy alternative that should at least be suggested for now.

**Comment by michaelsembwever** [comment] 2021-01-05 14:12
An intuitive failure message explaining Docker Desktop isn't supported would be enough for me (would have saved me much time), preferrably to a link to more info (so I could fix/implement it if i wanted to…)

**Comment by burmanm** [comment] 2021-02-04 16:42
For information, using the current version of k8ssandra and Docker for Desktop 3.1.0, the following helm install command is enough to solve the issues:

``helm install demo charts/k8ssandra --set cassandra.cassandraLibDirVolume.storageClass=hostpath``

We can mention this one in the docs if necessary. I haven't hit other issues.

**Comment by jdonenine** [comment] 2021-02-05 14:56
Going to close this issue as @burmanm has provided the solution to the core issue.  We will include some additional context on this through the doc updates mentioned above as well.

**Closed by jdonenine** 2021-02-05 14:56 UTC
Labels: bug, needs-triage
