### ISSUE TITLE
K8SSAND-987 ⁃ Support for upcoming Reaper 3.0 release

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra#1143] opened 2021-10-20 02:36 UTC
**Is your feature request related to a problem? Please describe.**
Add support for the upcoming Reaper 3.0 release.

**Additional context**
Depending on the features from Reaper 3.0 to be exposed, this ticket may be broken out into multiple with specific scope.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-987) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-1.4.0
┆Issue Number: K8SSAND-987
┆Priority: Medium

**Comment by jdonenine** [comment] 2021-11-10 13:14
Yup @Miles-Garnsey, thanks for digging through this, it feels like something we'd be better off addressing in K8ssandra operator as we migrate the reaper operator functionality. 

@jsanda @adutra what do you all think about things here?

**Comment by adutra** [comment] 2021-11-10 15:42
> The autoscheduling is enabled via cassandra-reaper.yaml. To overwrite this file in the container we need to be able to mount a configmap as a volume in the Reaper pod.

Is this something new in Reaper 3.0? From what I see in reaper-operator, autoscheduling is currently being handled with environment variables, see [here](https://github.com/k8ssandra/reaper-operator/blob/637cb522d19fb106deef465408f175435c56aae5/pkg/reconcile/reconcilers.go#L451-L494).

I'm not sure either we need this podTemplateSpec field? In the worst case, that is, if we really need a configmap + volume mount, couldn't we just create the configmap as part of the reconcile logic, then declare a volumeMount in the pod template?

In any case, as far as the work I'm doing in K8ssandra-operator is concerned, I will watch for changes in Reaper 3.0 and adapt accordingly.

**Comment by jsanda** [comment] 2021-11-10 15:49
In the Reaper image the auto scheduling properties are configurable via env vars. See [here](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/docker/cassandra-reaper.yml#L44).

Since the auto scheduling properties can be configured via env vars, we could add corresponding properties to the Reaper CRD. The Reaper controller would then set the env vars in the Reaper Deployment. I think this would be an easier approach than a ConfigMap. 

Either way, I would favor punting on this especially now that the migration of reaper-operator has started. My preference would be to address it once the migration into k8ssandra-operator is done.

**Comment by adutra** [comment] 2021-11-10 17:23
Also, I believe auto scheduling properties are already present in the Reaper CRD, see [here](https://github.com/k8ssandra/reaper-operator/blob/1583bcb3a5938017117f17e82ffbc54ae5ff9986/api/v1alpha1/reaper_types.go#L60-L68). In any case, I copied these properties over to the new Reaper CRD in k8ssandra-operator.

**Comment by Miles-Garnsey** [comment] 2021-11-10 23:36
So there are lots of ways to tackle this:

1. Configure autoscheduling using CR fields. The operator's reconciliation loops need to be updated to allow for this, we then have to make corresponding changes in k8ssandra's helm charts to move it forward.
2. Add a podTemplateSpec to reaper-operator's CRs. K8ssandra helm charts can then inject env vars or mount a configmap to configure autoscheduling. 
3. Add an env vars field to reaper-operator CRs, k8ssandra helm charts can then configure them.

I prefer option 2 because I think that podTemplateSpec should always be configurable to ensure that operators aren't getting in the way of configuration. 

But I also think that given that the scope of this is expanding and reaper-operator is going to be retired eventually, we should probably de-prioritise this. I think there's consensus from John and Jeff, so will close this ticket.

**Closed by Miles-Garnsey** 2021-11-10 23:36 UTC
Labels: enhancement, component:reaper

**Comment by jsanda** [comment] 2021-11-10 23:44
@Miles-Garnsey as @adutra pointed out, auto scheduling properties are already in the CRD. The operator already configures env vars for the auto scheduling properties. See [here](https://github.com/k8ssandra/reaper-operator/blob/master/pkg/reconcile/reconcilers.go#L465). 

I think it is already configurable in the chart. See [here](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L544). We may need some doc updates with examples.

**Comment by Miles-Garnsey** [comment] 2021-11-10 23:46
Do you want me to re-open this then @jsanda ?

**Comment by jsanda** [comment] 2021-11-10 23:54
After having looked into it a bit, I wonder what needs to be done with respect to auto scheduling.

**Comment by Miles-Garnsey** [comment] 2021-11-11 00:25
@adejanovski sent me a very good set of defaults for Cassandra 3x and 4x (reproduced below). 

That should be our target for a default config, and then we should allow the user to customise these defaults if desired. But from my understanding all of this should be going into k8ssandra-operator in any event, and (AFAIK) the reaper controller isn't ready yet.

**From Alexander:**

Then, with Cassandra 3.11, we want those autoscheduled repairs to be full and adaptive. That should give the following block:
```
autoScheduling:
  enabled: true
  initialDelayPeriod: PT15S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H
  adaptive: true

With Cassandra 4.0.0, we want them to be incremental and to trigger when 10% of the data is unrepaired:
```
autoScheduling:
  enabled: true
  initialDelayPeriod: PT15S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H
  incremental: true
  percentUnrepairedThreshold: 10
```

**Comment by jsanda** [comment] 2021-11-11 00:26
Good to know. We could configure those defaults in the Helm chart. wdyt?

**Comment by Miles-Garnsey** [comment] 2021-11-11 02:00
IMO:

1. the settings should be pulled out of the CRD and reconciliation loop since they are static and we can simplify this.
2. we should have a podTemplateSpec which we can use to customise the reaper pods.
3. as you say, Helm / kustomize should be used to create configmaps or env variables via the new podTemplateSpec.

This allows the most configurability and is more consistent with the way cass-operator works.

**Comment by jsanda** [comment] 2021-11-11 02:19
Why are the settings static? Aren't the values you share just defaults?

I am 👎 on having a podTemplateSpec for a couple reasons. First, reaper-operator already supports configuring auto scheduling. Secondly, I am actually not a fan of cass-operator's podTemplateSpec property for several reasons. It exposes and requires the user to be familiar with implementation details that could change from one release to the next. For example, suppose the next release of cass-operator adds an init container that changes the ordinal index of the init containers. This could easily break users. The podTemplateSpec field increases the complexity of the code involved which makes it harder to to introduce changes. 

When I mentioned configuring the defaults via Helm, it doesn't involve or require creating ConfigMaps or setting env vars. Actually, I checked the Reaper template (see [here](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/templates/reaper/reaper.yaml#L16)) and the only change that should be required is configuring the defaults in values.yaml. I don't think there is anything else that needs to be done.

**Comment by Miles-Garnsey** [comment] 2021-11-11 04:00
> Why are the settings static? Aren't the values you share just defaults?

Any changes require a restart of the reaper container AFAIK. This isn't a case where things are changing at runtime and need to be reconciled back, the container starts with certain settings and keeps them until next restart. So ConfigMap is a fine solution here and allows users to configure things using native k8s objects.

> Secondly, I am actually not a fan of cass-operator's podTemplateSpec property for several reasons. It exposes and requires the user to be familiar with implementation details that could change from one release to the next. For example, suppose the next release of cass-operator adds an init container that changes the ordinal index of the init containers. This could easily break users. The podTemplateSpec field increases the complexity of the code involved which makes it harder to to introduce changes.

My view is that all CRs which create child pods should always have a podTemplateSpec override. This is informed by my experience with operators which do not have this facility - which I have generally found makes them useless due to lack of configurability.

Your example opens a can of worms, but it doesn't support your argument. The `initContainers` and `containers` arrays within the [podSpec](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podspec-v1-core) both use a merge patch strategy with name as the key. Index changes do not affect the way that the podTemplateSpec is patched, assuming we are patching correctly. 

Having glanced through the [code](https://github.com/k8ssandra/cass-operator/blob/master/pkg/reconciliation/construct_statefulset.go#L151) I actually can't tell if we are patching correctly since this section is very convoluted. The use of `append` [here](https://github.com/k8ssandra/cass-operator/blob/master/pkg/reconciliation/construct_podtemplatespec.go#L531) makes me suspect not. In particular the fact that many fields are defined in both the CassDC CR as well as the podTemplateSpec is not optimal and leads to a lot of complexity in my view.

In any event, our failure to take advantage of proper merge behaviour for these types doesn't diminish the fact that users need configurability.

> When I mentioned configuring the defaults via Helm, it doesn't involve or require creating ConfigMaps or setting env vars. Actually, I checked the Reaper template (see here) and the only change that should be required is configuring the defaults in values.yaml. I don't think there is anything else that needs to be done.

That's not correct. The current CR does not have settings for -

* adaptive
* incremental
* percentUnrepairedThreshold

So this is not only a helm change and would require changes to the CR and controller first. 

Because I think this design is suboptimal in the first instance (why do these things need to be reconciled if they can't be changed post startup?) I think we should review the approach in a more wholistic way.

**Comment by jsanda** [comment] 2021-11-11 05:14
>Any changes require a restart of the reaper container AFAIK. This isn't a case where things are changing at runtime and need to be reconciled back, the container starts with certain settings and keeps them until next restart. So ConfigMap is a fine solution here and allows users to configure things using native k8s objects.

Not sure I follow, but updating the auto scheduling properties in the Reaper object should trigger an update of the Deployment.

>My view is that all CRs which create child pods should always have a podTemplateSpec override. This is informed by my experience with operators which do not have this facility - which I have generally found makes them useless due to lack of configurability.

I absolutely agree about the need for configurability, and I strongly disagress that all CRs which create pods should expose a PodTemplateSpec 😄  The custom resource is a higher level abstraction. The underlying objects used are an implementation detail. In some cases exposing a PodTemplateSpec may make sense, but I think it should be done with careful consideration.

>Your example opens a can of worms, but it doesn't support your argument.
>...
>Having glanced through the code I actually can't tell if we are patching correctly since this section is very convoluted. 

You kinda made my point 😉  

I think it is safer to try and put abstractions in place for things that need to be made configurable vs opening up the implementation. It also can simplify the development and maintenance of the code involved. 

>That's not correct. The current CR does not have settings for -
> * adaptive
> * incremental
> * percentUnrepairedThreshold

Thanks for pointing them out. It should be pretty straightforward to add them though since the framework is already in place. And to be clear, I am not necessarily opposed to a ConfigMap approach. For this repo and k8ssandra 1.x, I think it is more practical to stick with what is currently in place and push any bigger changes into k8ssandra-operator.

**Comment by Miles-Garnsey** [comment] 2021-11-11 06:29
> The custom resource is a higher level abstraction. The underlying objects used are an implementation detail. 

I strongly disagree with this. That is not the way that users view Kubernetes resources in my experience. Typically an operator is there to orchestrate an application in a container, and the ability to deeply configure that application is critical. If we start taking that capability away, then the incentive to use the operator is much diminished.

Users do not want operators to manage "abstract objects", they want to automate their application. 

For example, if you want your controllers to completely reconcile the pod state to a fixed state set by the CR, you'd be taking away the capability to run things like Istio (which injects a sidecar that would get reconciled away). 

I know that your proposal doesn't cause this problem because Istio uses a webhook instead of a podTemplateSpec, but there are analogous cases e.g. additional Java agents and the likes.

**Comment by adutra** [comment] 2021-11-12 09:48
> @adejanovski sent me a very good set of defaults for Cassandra 3x and 4x (reproduced below).

That's indeed extremely valuable. I will make those values the default ones in the new Reaper controller.

@adejanovski how do you set/specify the following settings? I don't see them being set through env vars... are they set on a per-operation basis?

1. adaptive
2. incremental
3. percentUnrepairedThreshold

**Comment by jsanda** [comment] 2021-11-12 15:39
@Miles-Garnsey it looks like @adutra ran into https://github.com/kubernetes-sigs/kubebuilder/issues/1140 while working on k8ssandra-operator, and I wanted to point on https://github.com/kubernetes-sigs/kubebuilder/issues/1140#issuecomment-562078502.

And let me provider another of where I think exposing the PodTemplateSpec is problematic. Suppose we decided to expose the PodTemplateSpec in k8ssandra. The CassandraDatacenter has everything under `/var/lib/cassandra/data` in a single volume. Let's say I decide to create separate PVC and volume mount for the data directory so as to put the commit log and data dirs on separate volumes. If I do this in the context of k8ssandra this could break things like backup/restore. I as a user therefore need to be intimately familiar with implementation details in order to make this change. Not good at all.
