### ISSUE TITLE
Cant login with super user creds

### ISSUE THREAD

**Issue by slayerjain** [k8ssandra/k8ssandra#503] opened 2021-03-05 19:12 UTC
## Bug Report

**Describe the bug**
Not able to login via superuser creds.
**To Reproduce**
1. Installed a fresh K8ssandra on EKS, along with other K8ssandra in other namespaces. 
2. Used dedicated nodes, so they've never restarted after creation. 
3. After few hours not able to login anymore with root creds. 
4. err:
`root@bash-7:/# cqlsh k8ssandra-k8s-dc2-service.k8ssandra-flux -u k8ssandra-superuser -p *password*
Connection error: ('Unable to connect to any servers', {'192.168.145.245': AuthenticationFailed('Failed to authenticate to 192.168.145.245: Error from server: code=0100 [Bad credentials] message="Provided username k8ssandra-superuser and/or password are incorrect"',), '192.168.132.190': AuthenticationFailed('Failed to authenticate to 192.168.132.190: Error from server: code=0100 [Bad credentials] message="Provided username k8ssandra-superuser and/or password are incorrect"',), '192.168.155.231': AuthenticationFailed('Failed to authenticate to 192.168.155.231: Error from server: code=0100 [Bad credentials] message="Provided username k8ssandra-superuser and/or password are incorrect"',)})`
5. tried nodetool repair
6. I was able to login for 5-10 mins, but then the same error soon after - cant login anymore. Maybe the node tool repair was unrelated, not sure. 

**Expected behavior**
Normal login
**Screenshots**

**Environment (please complete the following information):**

* Helm charts version info

`$ helm ls -A` 

```
k8ssandra-backup          	k8ssandra-flux	4       	2021-03-02 20:19:13.918109289 +0000 UTC	deployed	backupcronv2-0.1.0      	1.16.0
k8ssandra-cluster-flux    	k8ssandra-flux	7       	2021-03-02 19:57:24.974720292 +0000 UTC	deployed	k8ssandra-1.0.0
```

* Helm charts user-supplied values

`$ helm get values RELEASE_NAME` 
```
USER-SUPPLIED VALUES:
cassandra:
  cassandraLibDirVolume:
    size: 100Gi
    storageClass: gp2
  clusterName: k8ssandra
  datacenters:
  - name: k8s-dc2
    num_tokens: 256
    racks:
    - name: r1
    - name: r2
    - name: r3
    size: 3
  resources: {}
  version: 3.11.7
kube-prometheus-stack:
  enabled: false
medusa:
  bucketName: k8s-staging
  bucketSecretProvided: false
  enabled: true
  storage: s3
  storage_properties:
    region: us-west-2
  storageSecret: ""
stargate:
  enabled: false
  ```

* Kubernetes version information:

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind: EKS via eksctl

**Additional context**

**Comment by jsanda** [comment] 2021-03-06 00:56
Hi @slayerjain 

Can you share the exact `nodetool repair` command that you ran? Also note that Reaper is installed by default. You should use Reaper run repairs instead of directly invoking `nodetool`.

Can you reproduce this behavior consistently?

**Comment by slayerjain** [comment] 2021-03-06 16:44
Hi @jsanda , I've asked a colleague to share the command. 

I've tried Reaper too. `system_auth` and `system_distributed` seem stuck. I ran it almost 24 hours ago. 
<img width="1137" alt="Screenshot 2021-03-06 at 10 10 47 PM" src="https://user-images.githubusercontent.com/12831254/110214142-4a990280-7ec9-11eb-9403-e9168b52ffb7.png">

**Comment by jsanda** [comment] 2021-03-06 17:15
Can you provide logs from the Reaper pod?

A Cassandra user/role is created for Reaper. The secret containing the credential by default is named `<cluster-name>-reaper`. You can get the decoded credentials with:

```
$ kubectl get secret <reaper-secret> -o json | jq -r '.data.username' | base64 --decode
$ kubectl get secret <reaper-secret> -o json | jq -r '.data.password' | base64 --decode
```
Can you get those credentials and see if you are able to log in?

**Comment by slayerjain** [comment] 2021-03-06 17:56
Thanks for the reply. Yes, I'm able to login via those creds. 

```
reaper@cqlsh> SELECT * FROM system_schema.keyspaces;

 keyspace_name       | durable_writes | replication
---------------------+----------------+-----------------------------------------------------------------------------------
         system_auth |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'k8s-dc2': '3'}
 temporal_visibility |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'k8s-dc2': '3'}
       system_schema |           True |                           {'class': 'org.apache.cassandra.locator.LocalStrategy'}
            temporal |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'k8s-dc2': '3'}
  system_distributed |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'k8s-dc2': '3'}
              system |           True |                           {'class': 'org.apache.cassandra.locator.LocalStrategy'}
           reaper_db |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'k8s-dc2': '3'}
       system_traces |           True | {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'k8s-dc2': '3'}

       ```
I'm attaching the logs. 
[Uploading logs-from-reaper-in-k8ssandra-cluster-flux-reaper-5b89494775-2cljf.txt…]()

**Comment by slayerjain** [comment] 2021-03-06 18:00
Interestingly I can now login via superuser creds too.

**Comment by slayerjain** [comment] 2021-03-06 18:13
I'm really curious what's causing these cycles of success and failure in auth.

**Comment by jsanda** [comment] 2021-03-06 18:22
>I'm really curious what's causing these cycles of success and failure in auth.

Has the cycle happened more than once?

**Comment by slayerjain** [comment] 2021-03-06 18:25
> Has the cycle happened more than once? 
Yep, things worked fine on first install. It stopped working about a day later. then we tried node tool repair and seemed to work again for 15 mins and we got locked out. We were still locked out 12 hours ago, while I was able to login now. 

Is it normal for reaper to be stuck at 416/424 segments for 12+ hours? Is there anything we could do about it?

**Comment by jsanda** [comment] 2021-03-06 18:35
Can you take a screenshot of the clusters page in the Reaper UI? In particular I want to see what IP addresses are reported and whether they are red or green.

I would also like to see the IP addresses of the Cassandra pods. You can get those with this:

```
$ kubectl get pods -o wide -l cassandra.datastax.com/cluster=k8ssandra
```

Thanks

John

**Comment by jsanda** [comment] 2021-03-06 18:53
>Is it normal for reaper to be stuck at 416/424 segments for 12+ hours? Is there anything we could do about it?

@adejanovski any suggestions what we might want to look for?

**Comment by slayerjain** [comment] 2021-03-06 19:01
```
➜  /tmp kubectl get pods -o wide -l cassandra.datastax.com/cluster=k8ssandra -n k8ssandra-flux
NAME                         READY   STATUS    RESTARTS   AGE     IP                NODE                                            NOMINATED NODE   READINESS GATES
k8ssandra-k8s-dc2-r1-sts-0   3/3     Running   0          3d22h   192.168.155.231   ip-192-168-128-80.us-west-2.compute.internal    <none>           <none>
k8ssandra-k8s-dc2-r2-sts-0   3/3     Running   0          3d22h   192.168.145.245   ip-192-168-158-211.us-west-2.compute.internal   <none>           <none>
k8ssandra-k8s-dc2-r3-sts-0   3/3     Running   0          3d22h   192.168.132.190   ip-192-168-142-103.us-west-2.compute.internal   <none>           <none>
```

Here's the screenshot: 
<img width="1441" alt="Screenshot 2021-03-07 at 12 28 59 AM" src="https://user-images.githubusercontent.com/12831254/110217837-5c37d580-7edc-11eb-9e40-e41ab81026e8.png">

**Comment by jsanda** [comment] 2021-03-06 19:56
Here are some of the errors I see in Reaper's log:

```
INFO   [2021-03-06 17:47:08,175] [k8ssandra:780ab6d0-7ddb-11eb-8e37-8b021a9566ea] i.c.s.RepairRunner - Failed grabbing metrics from 192.168.159.112
java.util.concurrent.ExecutionException: io.cassandrareaper.ReaperException: no host could be reached through JMX

...

ERROR  [2021-03-06 17:47:08,217] [k8ssandra:780ab6d0-7ddb-11eb-8e37-8b021a9566ea] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 192.168.159.190:7199
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 192.168.159.190:7199

...

INFO   [2021-03-06 17:47:08,230] [k8ssandra:780ab6d0-7ddb-11eb-8e37-8b021a9566ea] i.c.s.RepairRunner - Failed grabbing metrics from 192.168.159.190
java.util.concurrent.ExecutionException: io.cassandrareaper.ReaperException: no host could be reached through JMX

...

ERROR  [2021-03-06 17:49:37,995] [pool-12-thread-10] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to 192.168.159.103:7199
java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to 192.168.159.103:7199
```
I do not think any of those IP addresses match the ones of your Cassandra pods. Have any of the pods been recreated?

Can I also see the output of `nodetool status`:

```
$ kubectl exec -it k8ssandra-k8s-dc2-r1-sts-0 -c cassandra -- nodetool -u <superuser-username> -pw <superuser-password> status
```

**Comment by slayerjain** [comment] 2021-03-06 20:17
> I do not think any of those IP addresses match the ones of your Cassandra pods. Have any of the pods been recreated?

I don't think so, as you can see all pods have similar ages.  We have multiple k8ssandra in different env, and we're facing similar problems with them too. Ahhh! some of these IPs belong to other k8ssandra clusters (maybe vanilla cass-operator too) in other namespaces - they all have their own cass-operator too with `clusterWideInstall` set to false. Could this be the problem? 

```
➜  logparser git:(master) ✗ kubectl get pods -o wide -l cassandra.datastax.com/cluster=k8ssandra --all-namespaces
NAMESPACE         NAME                         READY   STATUS    RESTARTS   AGE     IP                NODE                                            NOMINATED NODE   READINESS GATES
k8ssandra-exp     k8ssandra-k8s-dc2-r1-sts-0   3/3     Running   0          25h     192.168.158.145   ip-192-168-140-211.us-west-2.compute.internal   <none>           <none>
k8ssandra-exp     k8ssandra-k8s-dc2-r2-sts-0   3/3     Running   0          9h      192.168.129.25    ip-192-168-157-101.us-west-2.compute.internal   <none>           <none>
k8ssandra-exp     k8ssandra-k8s-dc2-r3-sts-0   3/3     Running   0          38h     192.168.159.112   ip-192-168-141-35.us-west-2.compute.internal    <none>           <none>
k8ssandra-flux    k8ssandra-k8s-dc2-r1-sts-0   3/3     Running   0          4d      192.168.155.231   ip-192-168-128-80.us-west-2.compute.internal    <none>           <none>
k8ssandra-flux    k8ssandra-k8s-dc2-r2-sts-0   3/3     Running   0          3d23h   192.168.145.245   ip-192-168-158-211.us-west-2.compute.internal   <none>           <none>
k8ssandra-flux    k8ssandra-k8s-dc2-r3-sts-0   3/3     Running   0          4d      192.168.132.190   ip-192-168-142-103.us-west-2.compute.internal   <none>           <none>
k8ssandra-flux2   k8ssandra-k8s-dc2-r1-sts-0   3/3     Running   0          3d22h   192.168.188.16    ip-192-168-170-11.us-west-2.compute.internal    <none>           <none>
k8ssandra-flux2   k8ssandra-k8s-dc2-r2-sts-0   3/3     Running   0          9h      192.168.159.190   ip-192-168-143-117.us-west-2.compute.internal   <none>           <none>
k8ssandra-flux2   k8ssandra-k8s-dc2-r3-sts-0   3/3     Running   0          4d      192.168.191.90    ip-192-168-166-211.us-west-2.compute.internal   <none>           <none>
```

> Can I also see the output of `nodetool status`:

```
20:15:52,460 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-tools.xml]
20:15:52,460 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
20:15:52,460 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:15:52,461 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/etc/cassandra/logback.xml]
20:15:52,597 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
20:15:52,602 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/etc/cassandra/logback.xml]] every 60 seconds.
20:15:52,602 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
20:15:52,606 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
20:15:52,799 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
20:15:52,804 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYSTEMLOG]
20:15:52,893 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@32cf48b7 - Will use zip compression
20:15:52,952 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:15:52,979 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
20:15:52,980 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
20:15:52,980 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - Failed to create parent directories for [/cassandra.logdir_IS_UNDEFINED/system.log]
20:15:52,980 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[SYSTEMLOG] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
	at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:148)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:72)
	at 	at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:213)
	at 	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:181)
	at 	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:54)
20:15:52,981 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
20:15:52,981 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DEBUGLOG]
20:15:52,982 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@d6da883 - Will use zip compression
20:15:52,985 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:15:52,986 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - Active log file name: cassandra.logdir_IS_UNDEFINED/debug.log
20:15:52,986 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - File property is set to [cassandra.logdir_IS_UNDEFINED/debug.log]
20:15:52,986 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - Failed to create parent directories for [/cassandra.logdir_IS_UNDEFINED/debug.log]
20:15:52,986 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DEBUGLOG] - openFile(cassandra.logdir_IS_UNDEFINED/debug.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/debug.log (No such file or directory)
	at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/debug.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:148)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:72)
	at 	at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:213)
	at 	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:181)
	at 	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:54)
20:15:52,986 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
20:15:52,989 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCDEBUGLOG]
20:15:52,993 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEBUGLOG] to ch.qos.logback.classic.AsyncAppender[ASYNCDEBUGLOG]
20:15:52,993 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCDEBUGLOG] - Attaching appender named [DEBUGLOG] to AsyncAppender.
20:15:52,994 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCDEBUGLOG] - Setting discardingThreshold to 0
20:15:52,994 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:15:52,996 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
20:15:52,998 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
20:15:52,999 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
20:15:52,999 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYSTEMLOG] to Logger[ROOT]
20:15:52,999 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
20:15:52,999 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCDEBUGLOG] to Logger[ROOT]
20:15:52,999 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.cassandra] to DEBUG
20:15:52,999 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
20:15:52,999 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
20:15:53,000 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@45afc369 - Registering current configuration as safe fallback point

Datacenter: k8s-dc2
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens       Owns (effective)  Host ID                               Rack
UN  192.168.129.25   63.82 MiB  1            0.4%              159317ed-46c1-4be0-9d76-afecee94d5f7  r2
UN  192.168.132.190  84.84 MiB  256          99.0%             1737d9d3-ec82-4a6d-a03d-31f2a784341b  r3
UN  192.168.159.112  64.15 MiB  1            1.0%              67a580f5-9b02-4c48-87e0-18dc99489a33  r3
UN  192.168.158.145  63.31 MiB  1            0.3%              1af9b76b-cdb6-4353-8dce-b700ae3ce538  r1
UN  192.168.145.245  85.59 MiB  256          99.6%             1ea48938-8508-4e23-a982-d8913dd66045  r2
UN  192.168.155.231  84.46 MiB  256          99.7%             8adf7c1b-6e76-4a15-b543-dba8ce729e9c  r1
```

**Comment by jsanda** [comment] 2021-03-06 20:37
>Ahhh! some of these IPs belong to other k8ssandra clusters (maybe vanilla cass-operator too) in other namespaces - they all have their own cass-operator too with clusterWideInstall set to false. Could this be the problem?

If the cluster names are the same then yes I think this could be the problem. You can install k8ssandra multiple times in different namespaces but the Helm release name has to be unique.  

In your chart configuration I noticed that you had `clusterName: k8ssandra`. In the future I suggest that you do not set `clusterName`. The cluster name defaults to the name of the Helm release. This would help prevent the sort of situation you are facing now.

**Comment by slayerjain** [comment] 2021-03-06 20:39
@jsanda Thanks a lot for the help. We'll fix the cluster names and report back 👯

**Comment by jsanda** [comment] 2021-04-19 14:43
Looks like we can close this. @slayerjain feel free to reopen if necessary.

**Closed by jsanda** 2021-04-19 14:43 UTC
Labels: bug, needs-triage
