### ISSUE TITLE
Grafana dashboard crashes after scaling up/down Cassandra node

### ISSUE THREAD

**Issue by navjyotnishant** [k8ssandra/k8ssandra#538] opened 2021-03-14 20:12 UTC
I have noticed Grafana dashboard start crashing as soon as we scale up/down number of Cassandra node.

I had to do rolling restart of deployment to make it working with upgraded environment.

**Comment by jsanda** [comment] 2021-03-15 02:12
Hi @navjyotnishant 

Can you please provide additional info including:

* The chart properties you used when installing
* How big is your Cassandra cluster?
* Does this error happening consistently?
* What version of the k8ssandra chart are you using?
* Can you provide Grafana logs?

**Comment by navjyotnishant** [comment] 2021-03-19 15:49
@jsanda 

Please find my comments:
**The chart properties you used when installing:**
I was working on POC environment for k8ssandra and followed the steps documented on website. - [Quick start](https://k8ssandra.io/docs/getting-started/)
**How big is your Cassandra cluster?**
I have started with default 1 node and later scaled it up to 3 node after which it failed - [Scale your Apache Cassandra](https://k8ssandra.io/docs/topics/provision-a-cluster/)
**Does this error happening consistently?**
I have waited for ~20min with a hope that once it get scaled up grafana will get settled as well but no luck, it was consistently timing out with error "underlying container <container-id> not found/running. I had to perform rolling restart-
` kubectl rollout restart deployment [deployment_name]`
**What version of the k8ssandra chart are you using?**
`k8ssandra-1.0.0`
**Can you provide Grafana logs?**
Let me reproduce and I will attach it here.

**Comment by jsanda** [comment] 2021-03-21 14:14
I did the following quick test:

```
$ helm install test k8ssandra/k8ssandra

# wait for C* pods to become ready

$ kubectl port-forward svc/test-grafana 3000:80

# verified I could see dashboards

$ helm upgrade test ./k8ssandra --set cassandra.datacenters\[0\].size=3,cassandra.datacenters\[0\].name=dc1

# wait for additional C* pods to become ready

# refresh dashboards a few times
```
The dashboards looked ok.

**Comment by navjyotnishant** [comment] 2021-03-28 13:29
Here is how I reproduce this:

**Provision:**
```
cassandra:
  version: "3.11.10"
  cassandraLibDirVolume:
    storageClass: local-path
    size: 5Gi
  allowMultipleNodesPerWorker: true
  heap:
   size: 1G
   newGenSize: 1G
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  datacenters:
  - name: dc1
    size: 1
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin123
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000

```

`helm install -f provision-k8ssandra.yaml k8ssandra k8ssandra/k8ssandra`

**Port forward**
`kubectl port-forward --address localhost svc/k8ssandra-grafana 8000:80 &`

Now Dashboard is accessible using credentials `admin/admin123`

**Increase Cassandra nodes**
```
cat k8ssandra-upgrade.yaml
cassandra:
  datacenters:
  - name: dc1
    size: 3
```
`helm upgrade -f k8ssandra-upgrade.yaml k8ssandra k8ssandra/k8ssandra`

**The dashboard crashed with following error:**
```


Handling connection for 8000
E0328 12:56:17.473412 3422190 portforward.go:400] an error occurred forwarding 8000 -> 3000: error forwarding port 3000 to pod af1d668135b52725d9280636a20b403f2c2636f5d7bcb6a5e14f38ddeb3c9413, uid : Error: No such container: af1d668135b52725d9280636a20b403f2c2636f5d7bcb6a5e14f38ddeb3c9413
Handling connection for 8000
Handling connection for 8000
E0328 12:56:24.438131 3422190 portforward.go:340] error creating error stream for port 8000 -> 3000: Timeout occured
E0328 12:56:24.442059 3422190 portforward.go:340] error creating error stream for port 8000 -> 3000: Timeout occured
E0328 12:56:24.443792 3422190 portforward.go:340] error creating error stream for port 8000 -> 3000: Timeout occured
E0328 12:56:32.361692 3422190 portforward.go:340] error creating error stream for port 8000 -> 3000: Timeout occured
```

I had to kill port forwarding and re instate the same and the dashboard came back online.
```
jobs -l
kill <port-forward-pid>
kubectl port-forward --address localhost svc/k8ssandra-grafana 8000:80 &
```

but the same credential (`admin/admin123`) did not work
, To fix this I had to add following in upgrade script and rerun upgrade.

```
cat k8ssandra-upgrade.yaml
cassandra:
  datacenters:
  - name: dc1
    size: 3
kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin123
```
`helm upgrade -f k8ssandra-upgrade.yaml k8ssandra k8ssandra/k8ssandra`

Again kill port forwarding and re instate the same and the dashboard came back online.
```
jobs -l
kill <port-forward-pid>
kubectl port-forward --address localhost svc/k8ssandra-grafana 8000:80 &
```

**Comment by jsanda** [comment] 2021-03-28 19:03
Those errors are not from Grafana. Those errors are basically just telling you that the `port-forward` connection timed out which is perfectly normal behavior.

**Comment by jsanda** [comment] 2021-04-06 13:42
Hi @navjyotnishant 

I am going to close this since this is normal, expected behavior. Please feel free to reopen if you are still having problems!

**Closed by jsanda** 2021-04-06 13:42 UTC
Labels: bug, component:grafana, needs-triage
